#![deny(unsafe_op_in_unsafe_fn)]

//! A deliberately small, native macOS overlay host.
//!
//! This crate is the AppKit containment boundary for ArenaNext. It has no
//! browser runtime, webview, game-process integration, screen-capture code,
//! file-system access, or Hearthstone-specific logic. It only owns an
//! `NSPanel` and renders a text model supplied by the caller.
//!
//! All public [`OverlayHost`] methods must run on the macOS main thread. The
//! type is deliberately `!Send` and `!Sync`; a caller with a background parser
//! should marshal model updates onto its main-thread event loop.

use std::{
    cell::{Cell, RefCell},
    error::Error,
    fmt,
    marker::PhantomData,
    rc::Rc,
    time::{Duration, Instant},
};

pub use arena_next_popup::StatusPopupModel;

use objc2::{
    AnyThread, DefinedClass, MainThreadMarker, MainThreadOnly, define_class, msg_send,
    rc::{Allocated, Retained},
    runtime::AnyObject,
};
use objc2_app_kit::{
    NSAlert, NSAlertStyle, NSAnyEventMask, NSApplication, NSApplicationActivationPolicy,
    NSAutoresizingMaskOptions, NSBackingStoreType, NSBox, NSButton, NSColor, NSEvent, NSEventMask,
    NSFont, NSImage, NSImageScaling, NSImageView, NSPanel, NSPopover, NSPopoverBehavior,
    NSProgressIndicator, NSProgressIndicatorStyle, NSScreen, NSStatusBar, NSStatusWindowLevel,
    NSTextField, NSVariableStatusItemLength, NSView, NSViewController, NSWindowCollectionBehavior,
    NSWindowStyleMask, NSWorkspace,
};
use objc2_foundation::{
    NSData, NSDate, NSDefaultRunLoopMode, NSObjectProtocol, NSPoint, NSRect, NSRectEdge, NSSize,
    NSString,
};

const CONTENT_PADDING: f64 = 12.0;
const ACTION_BUTTON_WIDTH: f64 = 112.0;
const ACTION_BUTTON_HEIGHT: f64 = 28.0;
const STATUS_ICON_PNG: &[u8] =
    include_bytes!("../../../../assets/icons/candidates/arena-helm-36.png");

#[derive(Debug, Default)]
struct ActionTargetIvars {
    command: Cell<u8>,
}

define_class!(
    #[unsafe(super = objc2_foundation::NSObject)]
    #[thread_kind = MainThreadOnly]
    #[ivars = ActionTargetIvars]
    struct ActionTarget;

    unsafe impl NSObjectProtocol for ActionTarget {}

    impl ActionTarget {
        #[unsafe(method(showPopup:))]
        fn show_popup(&self, _sender: Option<&AnyObject>) {
            self.ivars().command.set(4);
        }

        #[unsafe(method(toggleOverlay:))]
        fn toggle_overlay(&self, _sender: Option<&AnyObject>) {
            self.ivars().command.set(1);
        }

        #[unsafe(method(toggleInteraction:))]
        fn toggle_interaction(&self, _sender: Option<&AnyObject>) {
            self.ivars().command.set(2);
        }

        #[unsafe(method(quitArenaNext:))]
        fn quit(&self, _sender: Option<&AnyObject>) {
            self.ivars().command.set(3);
        }

        #[unsafe(method(showFixDeckHelp:))]
        fn show_fix_deck_help(&self, _sender: Option<&AnyObject>) {
            self.ivars().command.set(5);
        }
    }
);

impl ActionTarget {
    fn new(mtm: MainThreadMarker) -> Retained<Self> {
        let this = Self::alloc(mtm).set_ivars(ActionTargetIvars::default());
        unsafe { msg_send![super(this), init] }
    }

    fn take_command(&self) -> Option<OverlayCommand> {
        match self.ivars().command.replace(0) {
            1 => Some(OverlayCommand::ToggleVisibility),
            2 => Some(OverlayCommand::ToggleInteraction),
            3 => Some(OverlayCommand::Quit),
            4 => Some(OverlayCommand::ShowPopup),
            5 => Some(OverlayCommand::FixDeckHelp),
            _ => None,
        }
    }
}

/// Commands generated by the native status menu or action affordance.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum OverlayCommand {
    /// Open the compact status card anchored near the menu-bar item.
    ShowPopup,
    /// Explain how to force Hearthstone to emit an authoritative deck snapshot.
    FixDeckHelp,
    ToggleVisibility,
    ToggleInteraction,
    Quit,
}

/// Bundle identifiers observed for retail macOS Hearthstone clients.
///
/// Current Unity-based builds report the first identifier; an older client
/// can report the legacy second identifier. This is only a frontmost-app
/// comparison, never a game-process attachment or inspection.
pub const HEARTHSTONE_BUNDLE_IDS: [&str; 2] = [
    "unity.Blizzard Entertainment.Hearthstone",
    "com.blizzard.hearthstone",
];

/// A rectangle in AppKit's global *point* coordinate system.
///
/// This intentionally uses logical points rather than screen-capture pixels.
/// The future window-tracking layer owns Retina scale and top-left-to-bottom-
/// left conversion before it calls [`OverlayHost::set_bounds`].
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct OverlayBounds {
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
}

/// One click-through score badge positioned over a visible draft offer.
#[derive(Clone, Debug, PartialEq)]
pub struct OfferScoreBadge {
    pub bounds: OverlayBounds,
    pub caption: String,
    pub detail: String,
    pub score: String,
    pub loading: bool,
}

impl OverlayBounds {
    pub const fn new(x: f64, y: f64, width: f64, height: f64) -> Self {
        Self {
            x,
            y,
            width,
            height,
        }
    }

    fn validate(self) -> Result<(), OverlayError> {
        if self.x.is_finite()
            && self.y.is_finite()
            && self.width.is_finite()
            && self.height.is_finite()
            && self.width > 0.0
            && self.height > 0.0
        {
            Ok(())
        } else {
            Err(OverlayError::InvalidBounds(self))
        }
    }

    fn ns_rect(self) -> NSRect {
        NSRect::new(
            NSPoint::new(self.x, self.y),
            NSSize::new(self.width, self.height),
        )
    }
}

/// The intentionally small render model for the first native overlay.
///
/// A richer, game-specific view model can be rendered above this component
/// later. Keeping this type text-only makes the platform host reusable and
/// keeps all Hearthstone state out of AppKit.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct OverlayModel {
    pub title: String,
    pub lines: Vec<String>,
    pub deck_rows: Vec<DeckRow>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct DeckRow {
    pub card_id: String,
    pub mana_cost: Option<u8>,
    pub name: String,
    pub count: u8,
    pub preview_image_path: Option<String>,
}

impl OverlayModel {
    /// Returns the text exactly as it is rendered by the current minimal view.
    pub fn display_text(&self) -> String {
        let mut lines = Vec::with_capacity(self.lines.len() + 1);
        if !self.title.trim().is_empty() {
            lines.push(self.title.as_str());
        }
        lines.extend(
            self.lines
                .iter()
                .map(String::as_str)
                .filter(|line| !line.trim().is_empty()),
        );
        lines.join("\n")
    }
}

/// Errors returned before AppKit is asked to mutate a window.
#[derive(Clone, Debug, PartialEq)]
pub enum OverlayError {
    /// AppKit windows and views may only be created and mutated on its main
    /// thread. This crate checks that invariant at every public entry point.
    NotOnMainThread,
    /// The status item was created without a button, so a popover cannot be anchored.
    StatusButtonUnavailable,
    /// The caller supplied a non-finite or non-positive AppKit frame.
    InvalidBounds(OverlayBounds),
    /// A tick loop with no delay would spin the main thread at 100% CPU.
    InvalidTickInterval,
}

impl fmt::Display for OverlayError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NotOnMainThread => {
                formatter.write_str("macOS overlay called off the main thread")
            }
            Self::StatusButtonUnavailable => {
                formatter.write_str("macOS status item has no button for popover anchoring")
            }
            Self::InvalidBounds(bounds) => write!(
                formatter,
                "invalid macOS overlay bounds: x={}, y={}, width={}, height={}",
                bounds.x, bounds.y, bounds.width, bounds.height
            ),
            Self::InvalidTickInterval => {
                formatter.write_str("macOS overlay tick interval must be greater than zero")
            }
        }
    }
}

impl Error for OverlayError {}

/// What [`OverlayHost::run_with_tick`] should do after a successful tick.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum TickControl {
    /// Keep servicing AppKit events and invoke the tick again after the interval.
    #[default]
    Continue,
    /// Leave the tick loop without terminating the application process.
    Stop,
}

/// A failure from the platform host or from a caller-supplied observer tick.
#[derive(Debug)]
pub enum RunWithTickError<E> {
    Overlay(OverlayError),
    Tick(E),
}

impl<E: fmt::Display> fmt::Display for RunWithTickError<E> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Overlay(error) => write!(formatter, "overlay error: {error}"),
            Self::Tick(error) => write!(formatter, "observer tick failed: {error}"),
        }
    }
}

impl<E: Error + 'static> Error for RunWithTickError<E> {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Overlay(error) => Some(error),
            Self::Tick(error) => Some(error),
        }
    }
}

/// A borderless, non-activating AppKit overlay panel.
///
/// The panel is configured for all Spaces and native fullscreen. It never
/// calls `activate`, `makeKeyAndOrderFront`, or any game-process API. Showing
/// it uses `orderFrontRegardless`, which orders the panel without activating
/// the assistant application.
pub struct OverlayHost {
    // Retain the application as long as this host exists. The leading
    // underscore documents that it is retained for AppKit lifetime, not read.
    _application: Retained<NSApplication>,
    panel: Retained<NSPanel>,
    fix_deck_panel: Retained<NSPanel>,
    offer_score_panels: Vec<Retained<NSPanel>>,
    offer_score_surfaces: Vec<Retained<NSBox>>,
    offer_score_captions: Vec<Retained<NSTextField>>,
    offer_score_details: Vec<Retained<NSTextField>>,
    offer_score_values: Vec<Retained<NSTextField>>,
    offer_score_spinners: Vec<Retained<NSProgressIndicator>>,
    label: Retained<NSTextField>,
    deck_row_labels: Vec<Retained<NSTextField>>,
    deck_rows: RefCell<Vec<DeckRow>>,
    preview_panel: Retained<NSPanel>,
    preview_image: Retained<NSImageView>,
    preview_status: Retained<NSTextField>,
    action_button: Retained<NSButton>,
    popup: Retained<NSPopover>,
    _popup_controller: Retained<NSViewController>,
    _popup_title: Retained<NSTextField>,
    popup_status: Retained<NSTextField>,
    popup_run: Retained<NSTextField>,
    popup_rows: Vec<Retained<NSTextField>>,
    _popup_quit: Retained<NSButton>,
    _popup_icon: Option<Retained<NSImageView>>,
    // Retaining the status item is essential: AppKit otherwise removes it
    // as soon as the last Rust reference is dropped.
    _status_item: Retained<objc2_app_kit::NSStatusItem>,
    _status_icon: Option<Retained<NSImage>>,
    action_target: Retained<ActionTarget>,
    // AppKit's objects are main-thread constrained. Keep that requirement
    // visible even if an upstream binding ever loosens its Send markers.
    _not_send_or_sync: PhantomData<Rc<()>>,
}

impl OverlayHost {
    /// Creates a transparent, click-through, non-activating overlay.
    ///
    /// The caller normally calls [`Self::show`] after setup and then runs its
    /// own AppKit event loop. Calling [`Self::run_event_loop`] is convenient
    /// for a small standalone native binary.
    pub fn new(bounds: OverlayBounds, model: &OverlayModel) -> Result<Self, OverlayError> {
        let main_thread = require_main_thread()?;
        bounds.validate()?;

        let application = NSApplication::sharedApplication(main_thread);
        // An accessory app has no Dock icon or normal app UI. This also makes
        // it less likely that the observer steals attention from Hearthstone.
        application.setActivationPolicy(NSApplicationActivationPolicy::Accessory);
        // The custom NSRunLoop pump below still needs AppKit's normal launch
        // lifecycle completed; without this, status-item clicks can render but
        // never enter menu tracking.
        application.finishLaunching();

        let allocated_panel: Allocated<NSPanel> = NSPanel::alloc(main_thread);
        let panel = NSPanel::initWithContentRect_styleMask_backing_defer(
            allocated_panel,
            bounds.ns_rect(),
            NSWindowStyleMask::Borderless | NSWindowStyleMask::NonactivatingPanel,
            NSBackingStoreType::Buffered,
            false,
        );
        configure_panel(&panel);

        let text = NSString::from_str(&model.display_text());
        let label = NSTextField::wrappingLabelWithString(&text, main_thread);
        configure_label(&label, bounds);

        // A small native affordance is always present in the lower-right of
        // the overlay. The panel remains click-through by default, so this
        // button becomes actionable only after the caller opts into
        // interaction with `set_click_through(false)`.
        let action_title = NSString::from_str("Fix Deck…");
        let action_target = ActionTarget::new(main_thread);
        let action_button = unsafe {
            NSButton::buttonWithTitle_target_action(
                &action_title,
                Some(&*action_target as &AnyObject),
                Some(objc2::sel!(showFixDeckHelp:)),
                main_thread,
            )
        };
        configure_action_button(&action_button);

        // A newly initialized NSPanel always has a content view. The AppKit
        // initializer is the only one used above, so this cannot be absent.
        let content_view: Option<Retained<NSView>> = panel.contentView();
        if let Some(content_view) = content_view {
            let label_view: &NSView = &label;
            content_view.addSubview(label_view);
        }

        let mut deck_row_labels = Vec::with_capacity(30);
        if let Some(content_view) = panel.contentView() {
            for _ in 0..30 {
                let row = NSTextField::labelWithString(&NSString::from_str(""), main_thread);
                configure_deck_row(&row);
                row.setHidden(true);
                content_view.addSubview(&row);
                deck_row_labels.push(row);
            }
        }

        let preview_panel = NSPanel::initWithContentRect_styleMask_backing_defer(
            NSPanel::alloc(main_thread),
            OverlayBounds::new(0.0, 0.0, 256.0, 384.0).ns_rect(),
            NSWindowStyleMask::Borderless | NSWindowStyleMask::NonactivatingPanel,
            NSBackingStoreType::Buffered,
            false,
        );
        configure_score_panel(&preview_panel);
        let preview_image = NSImageView::initWithFrame(
            NSImageView::alloc(main_thread),
            NSRect::new(NSPoint::new(0.0, 0.0), NSSize::new(256.0, 384.0)),
        );
        preview_image.setImageScaling(NSImageScaling::ScaleProportionallyUpOrDown);
        let preview_status = NSTextField::wrappingLabelWithString(
            &NSString::from_str("Loading card preview…"),
            main_thread,
        );
        configure_preview_status(&preview_status);
        if let Some(content_view) = preview_panel.contentView() {
            content_view.addSubview(&preview_image);
            content_view.addSubview(&preview_status);
        }

        // Keep the large text panel click-through, but place the recovery
        // affordance in its own tiny non-activating panel. Only the button's
        // rectangle receives mouse events, so normal Hearthstone interaction
        // remains untouched everywhere else.
        let fix_deck_panel = NSPanel::initWithContentRect_styleMask_backing_defer(
            NSPanel::alloc(main_thread),
            fix_deck_panel_frame(bounds),
            NSWindowStyleMask::Borderless | NSWindowStyleMask::NonactivatingPanel,
            NSBackingStoreType::Buffered,
            false,
        );
        configure_panel(&fix_deck_panel);
        fix_deck_panel.setIgnoresMouseEvents(false);
        if let Some(content_view) = fix_deck_panel.contentView() {
            let action_view: &NSView = &action_button;
            content_view.addSubview(action_view);
        }

        let mut offer_score_panels = Vec::with_capacity(3);
        let mut offer_score_surfaces = Vec::with_capacity(3);
        let mut offer_score_captions = Vec::with_capacity(3);
        let mut offer_score_details = Vec::with_capacity(3);
        let mut offer_score_values = Vec::with_capacity(3);
        let mut offer_score_spinners = Vec::with_capacity(3);
        for _ in 0..3 {
            let score_panel = NSPanel::initWithContentRect_styleMask_backing_defer(
                NSPanel::alloc(main_thread),
                OverlayBounds::new(0.0, 0.0, 1.0, 1.0).ns_rect(),
                NSWindowStyleMask::Borderless | NSWindowStyleMask::NonactivatingPanel,
                NSBackingStoreType::Buffered,
                false,
            );
            configure_score_panel(&score_panel);
            let surface = NSBox::initWithFrame(
                NSBox::alloc(main_thread),
                OverlayBounds::new(0.0, 0.0, 1.0, 1.0).ns_rect(),
            );
            configure_score_surface(&surface);
            let caption =
                NSTextField::labelWithString(&NSString::from_str("READING OFFER"), main_thread);
            configure_score_caption(&caption);
            let detail =
                NSTextField::labelWithString(&NSString::from_str("WAITING FOR OCR"), main_thread);
            configure_score_detail(&detail);
            let value = NSTextField::labelWithString(&NSString::from_str("…"), main_thread);
            configure_score_value(&value);
            let spinner = NSProgressIndicator::initWithFrame(
                NSProgressIndicator::alloc(main_thread),
                NSRect::new(NSPoint::new(0.0, 0.0), NSSize::new(22.0, 22.0)),
            );
            spinner.setStyle(NSProgressIndicatorStyle::Spinning);
            spinner.setIndeterminate(true);
            spinner.setDisplayedWhenStopped(false);
            spinner.setHidden(true);
            if let Some(content_view) = score_panel.contentView() {
                content_view.addSubview(&surface);
                content_view.addSubview(&caption);
                content_view.addSubview(&detail);
                content_view.addSubview(&value);
                content_view.addSubview(&spinner);
            }
            offer_score_panels.push(score_panel);
            offer_score_surfaces.push(surface);
            offer_score_captions.push(caption);
            offer_score_details.push(detail);
            offer_score_values.push(value);
            offer_score_spinners.push(spinner);
        }

        let popup_bounds = OverlayBounds::new(0.0, 0.0, 320.0, 250.0);
        let popup_root = NSView::initWithFrame(NSView::alloc(main_thread), popup_bounds.ns_rect());
        let popup_title = popup_label(
            "HearthAI",
            NSRect::new(NSPoint::new(78.0, 204.0), NSSize::new(205.0, 28.0)),
            20.0,
            &NSColor::whiteColor(),
            main_thread,
        );
        let popup_status = popup_label(
            "● Offline",
            NSRect::new(NSPoint::new(78.0, 180.0), NSSize::new(120.0, 18.0)),
            12.0,
            &NSColor::colorWithCalibratedRed_green_blue_alpha(0.95, 0.55, 0.35, 1.0),
            main_thread,
        );
        popup_root.addSubview(&popup_title);
        popup_root.addSubview(&popup_status);
        let default_popup = StatusPopupModel::default();
        let run_card = NSBox::initWithFrame(
            NSBox::alloc(main_thread),
            NSRect::new(NSPoint::new(218.0, 170.0), NSSize::new(88.0, 56.0)),
        );
        run_card.setBoxType(objc2_app_kit::NSBoxType::Custom);
        run_card.setFillColor(&NSColor::colorWithCalibratedRed_green_blue_alpha(
            0.55, 0.40, 0.12, 0.28,
        ));
        run_card.setBorderColor(&NSColor::colorWithCalibratedRed_green_blue_alpha(
            0.95, 0.70, 0.25, 0.55,
        ));
        run_card.setBorderWidth(1.0);
        run_card.setCornerRadius(8.0);
        popup_root.addSubview(&run_card);
        let run_caption = popup_label(
            "ARENA RUN",
            NSRect::new(NSPoint::new(226.0, 206.0), NSSize::new(74.0, 10.0)),
            8.0,
            &NSColor::colorWithCalibratedRed_green_blue_alpha(1.0, 0.82, 0.42, 1.0),
            main_thread,
        );
        let popup_run = popup_label(
            &default_popup.run_label(),
            NSRect::new(NSPoint::new(226.0, 180.0), NSSize::new(74.0, 20.0)),
            12.0,
            &NSColor::whiteColor(),
            main_thread,
        );
        popup_root.addSubview(&run_caption);
        popup_root.addSubview(&popup_run);
        let mut popup_rows = Vec::new();
        for (index, row) in default_popup.rows().into_iter().enumerate() {
            let y = 146.0 - (index as f64 * 29.0);
            let card = NSBox::initWithFrame(
                NSBox::alloc(main_thread),
                NSRect::new(NSPoint::new(14.0, y - 4.0), NSSize::new(292.0, 26.0)),
            );
            card.setBoxType(objc2_app_kit::NSBoxType::Custom);
            card.setFillColor(&NSColor::colorWithCalibratedWhite_alpha(0.12, 0.75));
            card.setBorderColor(&NSColor::colorWithCalibratedWhite_alpha(1.0, 0.08));
            card.setBorderWidth(1.0);
            card.setCornerRadius(6.0);
            popup_root.addSubview(&card);
            let label = popup_label(
                &format!("{}   {}", row.label, row.value),
                NSRect::new(NSPoint::new(22.0, y + 1.0), NSSize::new(276.0, 17.0)),
                12.0,
                &NSColor::colorWithCalibratedWhite_alpha(0.92, 1.0),
                main_thread,
            );
            popup_root.addSubview(&label);
            popup_rows.push(label);
        }
        let quit_title = NSString::from_str("Exit");
        let popup_quit = unsafe {
            NSButton::buttonWithTitle_target_action(
                &quit_title,
                Some(&*action_target as &AnyObject),
                Some(objc2::sel!(quitArenaNext:)),
                main_thread,
            )
        };
        popup_quit.setFrame(NSRect::new(
            NSPoint::new(190.0, 12.0),
            NSSize::new(116.0, 26.0),
        ));
        popup_quit.setFont(Some(&NSFont::systemFontOfSize(11.0)));
        popup_quit.setBordered(true);
        popup_quit.setToolTip(Some(&NSString::from_str("Exit HearthAI")));
        popup_root.addSubview(&popup_quit);
        let popup_icon_image =
            NSImage::initWithData(NSImage::alloc(), &NSData::with_bytes(STATUS_ICON_PNG));
        let popup_icon = popup_icon_image.as_ref().map(|icon| {
            let image_view = NSImageView::imageViewWithImage(icon, main_thread);
            image_view.setFrame(NSRect::new(
                NSPoint::new(18.0, 180.0),
                NSSize::new(48.0, 48.0),
            ));
            image_view
        });
        if let Some(icon) = popup_icon.as_ref() {
            let icon_view: &NSView = icon;
            popup_root.addSubview(icon_view);
        }
        let popup = NSPopover::new(main_thread);
        popup.setBehavior(NSPopoverBehavior::Transient);
        popup.setAnimates(true);
        popup.setContentSize(NSSize::new(320.0, 250.0));
        let popup_controller = NSViewController::new(main_thread);
        popup_controller.setView(&popup_root);
        popup.setContentViewController(Some(&popup_controller));

        let status_bar = NSStatusBar::systemStatusBar();
        let status_item = status_bar.statusItemWithLength(NSVariableStatusItemLength);
        // Embed the selected helmet mark so the status item is independent of
        // the app's current working directory. Keep the glyph as a fallback
        // if AppKit cannot decode the PNG on an older system.
        let status_icon =
            NSImage::initWithData(NSImage::alloc(), &NSData::with_bytes(STATUS_ICON_PNG));
        if let Some(button) = status_item.button(main_thread) {
            if let Some(icon) = status_icon.as_ref() {
                icon.setSize(NSSize::new(18.0, 18.0));
                button.setImage(Some(icon));
                button.setTitle(&NSString::from_str(""));
            } else {
                button.setTitle(&NSString::from_str("◈"));
            }
            button.setToolTip(Some(&NSString::from_str("HearthAI")));
            // The primary click opens the rich status card directly. The old
            // intermediate menu made the icon feel like a dead system item.
            unsafe {
                button.setTarget(Some(&*action_target as &AnyObject));
                button.setAction(Some(objc2::sel!(showPopup:)));
            }
        }
        Ok(Self {
            _application: application,
            panel,
            fix_deck_panel,
            offer_score_panels,
            offer_score_surfaces,
            offer_score_captions,
            offer_score_details,
            offer_score_values,
            offer_score_spinners,
            label,
            deck_row_labels,
            deck_rows: RefCell::new(Vec::new()),
            preview_panel,
            preview_image,
            preview_status,
            action_button,
            popup,
            _popup_controller: popup_controller,
            _popup_title: popup_title,
            popup_status,
            popup_run,
            popup_rows,
            _popup_quit: popup_quit,
            _popup_icon: popup_icon,
            _status_item: status_item,
            _status_icon: status_icon,
            action_target,
            _not_send_or_sync: PhantomData,
        })
    }

    /// Places the overlay above normal application windows without activating
    /// the assistant or taking keyboard focus from Hearthstone.
    pub fn show(&self) -> Result<(), OverlayError> {
        require_main_thread()?;
        self.panel.orderFrontRegardless();
        self.fix_deck_panel.orderFrontRegardless();
        self.update_hover_preview()?;
        Ok(())
    }

    /// Hides the overlay while retaining its model and native window.
    pub fn hide(&self) -> Result<(), OverlayError> {
        require_main_thread()?;
        self.panel.orderOut(None);
        self.fix_deck_panel.orderOut(None);
        self.hide_offer_scores()?;
        self.preview_panel.orderOut(None);
        Ok(())
    }

    /// Updates and reveals the three click-through score badges. Their bounds
    /// are AppKit global points, just like the main overlay bounds.
    pub fn show_offer_scores(&self, badges: &[OfferScoreBadge; 3]) -> Result<(), OverlayError> {
        require_main_thread()?;
        for (index, badge) in badges.iter().enumerate() {
            let panel = &self.offer_score_panels[index];
            badge.bounds.validate()?;
            panel.setFrame_display(badge.bounds.ns_rect(), true);
            let width = badge.bounds.width;
            let height = badge.bounds.height;
            let inset = 10.0;
            let value_width = (width * 0.28).clamp(50.0, 78.0);
            let copy_width = (width - value_width - inset * 2.5).max(1.0);
            self.offer_score_surfaces[index].setFrame(NSRect::new(
                NSPoint::new(1.0, 1.0),
                NSSize::new((width - 2.0).max(1.0), (height - 2.0).max(1.0)),
            ));
            self.offer_score_captions[index].setFrame(NSRect::new(
                NSPoint::new(inset, (height * 0.52).max(1.0)),
                NSSize::new(copy_width, (height * 0.30).max(1.0)),
            ));
            self.offer_score_details[index].setFrame(NSRect::new(
                NSPoint::new(inset, (height * 0.18).max(1.0)),
                NSSize::new(copy_width, (height * 0.25).max(1.0)),
            ));
            self.offer_score_values[index].setFrame(NSRect::new(
                NSPoint::new(width - value_width - inset, (height * 0.12).max(1.0)),
                NSSize::new(value_width, (height * 0.72).max(1.0)),
            ));
            let spinner_size = height.clamp(18.0, 24.0);
            self.offer_score_spinners[index].setFrame(NSRect::new(
                NSPoint::new(
                    width - inset - value_width / 2.0 - spinner_size / 2.0,
                    (height - spinner_size) / 2.0,
                ),
                NSSize::new(spinner_size, spinner_size),
            ));
            self.offer_score_captions[index].setStringValue(&NSString::from_str(&badge.caption));
            self.offer_score_details[index].setStringValue(&NSString::from_str(&badge.detail));
            if badge.loading {
                self.offer_score_values[index].setHidden(true);
                self.offer_score_spinners[index].setHidden(false);
                unsafe { self.offer_score_spinners[index].startAnimation(None) };
            } else {
                unsafe { self.offer_score_spinners[index].stopAnimation(None) };
                self.offer_score_spinners[index].setHidden(true);
                self.offer_score_values[index].setStringValue(&NSString::from_str(&badge.score));
                self.offer_score_values[index].setHidden(false);
            }
            panel.orderFrontRegardless();
        }
        Ok(())
    }

    pub fn hide_offer_scores(&self) -> Result<(), OverlayError> {
        require_main_thread()?;
        for panel in &self.offer_score_panels {
            panel.orderOut(None);
        }
        Ok(())
    }

    /// Converts ScreenCaptureKit's top-left desktop coordinates to AppKit's
    /// bottom-left global coordinates. Current Hearthstone capture selects the
    /// primary game surface; the containing screen's top edge is used when it
    /// can be identified, with the main screen as a safe fallback.
    pub fn bounds_from_top_left(
        &self,
        x: f64,
        y: f64,
        width: f64,
        height: f64,
    ) -> Result<OverlayBounds, OverlayError> {
        let main_thread = require_main_thread()?;
        let screens = NSScreen::screens(main_thread);
        let center_x = x + width / 2.0;
        let mut screen_top = None;
        for index in 0..screens.count() {
            let frame = screens.objectAtIndex(index).frame();
            if center_x >= frame.origin.x && center_x <= frame.origin.x + frame.size.width {
                screen_top = Some(frame.origin.y + frame.size.height);
                break;
            }
        }
        let top = screen_top
            .or_else(|| NSScreen::mainScreen(main_thread).map(|screen| screen.frame().size.height))
            .unwrap_or(0.0);
        let bounds = OverlayBounds::new(x, top - y - height, width, height);
        bounds.validate()?;
        Ok(bounds)
    }

    /// Shows the compact status card without activating the application.
    pub fn show_popup(&self) -> Result<(), OverlayError> {
        require_main_thread()?;
        let Some(button) = self._status_item.button(require_main_thread()?) else {
            return Err(OverlayError::StatusButtonUnavailable);
        };
        let button_view: &NSView = &button;
        self.popup.showRelativeToRect_ofView_preferredEdge(
            button_view.bounds(),
            button_view,
            NSRectEdge::MaxY,
        );
        Ok(())
    }

    pub fn hide_popup(&self) -> Result<(), OverlayError> {
        require_main_thread()?;
        self.popup.close();
        Ok(())
    }

    /// Shows the non-destructive Arena deck recovery instructions.
    pub fn show_fix_deck_help(&self) -> Result<(), OverlayError> {
        let main_thread = require_main_thread()?;
        let alert = NSAlert::new(main_thread);
        alert.setAlertStyle(NSAlertStyle::Informational);
        alert.setMessageText(&NSString::from_str("Fix Arena deck"));
        alert.setInformativeText(&NSString::from_str(
            "In Hearthstone, leave Arena to the main menu, then re-enter Arena. Hearthstone will emit a complete current-deck snapshot, and ArenaNext will replace missing or incorrect cards automatically. You do not need to retire the run.",
        ));
        alert.addButtonWithTitle(&NSString::from_str("Got it"));
        alert.runModal();
        Ok(())
    }

    pub fn update_popup(&self, model: &StatusPopupModel) -> Result<(), OverlayError> {
        require_main_thread()?;
        // The title already establishes the Hearthstone context. Keep this
        // line short so it cannot truncate beside the run badge.
        let status = NSString::from_str(&format!(
            "● {}",
            match model.hearthstone_label() {
                "Running" => "Running",
                "Permission required" => "Permission needed",
                _ => "Offline",
            }
        ));
        self.popup_status.setStringValue(&status);
        self.popup_run
            .setStringValue(&NSString::from_str(&model.run_label()));
        for (label, row) in self.popup_rows.iter().zip(model.rows()) {
            label.setStringValue(&NSString::from_str(&format!(
                "{}   {}",
                row.label, row.value
            )));
        }
        Ok(())
    }

    /// Enables or disables click-through mode.
    ///
    /// The default is `true`. The eventual settings UI may temporarily turn it
    /// off to let a user reposition or inspect the overlay; it must restore
    /// `true` before regular game use.
    pub fn set_click_through(&self, enabled: bool) -> Result<(), OverlayError> {
        require_main_thread()?;
        self.panel.setIgnoresMouseEvents(enabled);
        Ok(())
    }

    /// Enables the lower-right native action surface. This is equivalent to
    /// `set_click_through(false)` and exists as a semantic API for future
    /// shared command dispatchers on macOS and Windows.
    pub fn set_interactive(&self, interactive: bool) -> Result<(), OverlayError> {
        self.set_click_through(!interactive)
    }

    /// Changes the label shown in the lower-right native action button.
    pub fn set_action_button_title(&self, title: &str) -> Result<(), OverlayError> {
        require_main_thread()?;
        let title = NSString::from_str(title);
        self.action_button.setTitle(&title);
        Ok(())
    }

    /// Returns and clears the next command selected in the status menu or
    /// lower-right button. Call this from the main-thread tick closure.
    pub fn take_command(&self) -> Result<Option<OverlayCommand>, OverlayError> {
        require_main_thread()?;
        Ok(self.action_target.take_command())
    }

    /// Repositions and resizes the overlay in AppKit global points.
    pub fn set_bounds(&self, bounds: OverlayBounds) -> Result<(), OverlayError> {
        require_main_thread()?;
        bounds.validate()?;
        self.panel.setFrame_display(bounds.ns_rect(), true);
        self.fix_deck_panel
            .setFrame_display(fix_deck_panel_frame(bounds), true);
        self.label.setFrame(label_frame(bounds));
        self.layout_deck_rows(bounds);
        self.action_button.setFrame(action_button_frame());
        Ok(())
    }

    /// Replaces the visible text without recreating the panel or changing
    /// focus. This is the normal render path for observer state updates.
    pub fn update_model(&self, model: &OverlayModel) -> Result<(), OverlayError> {
        require_main_thread()?;
        let text = NSString::from_str(&model.display_text());
        self.label.setStringValue(&text);
        *self.deck_rows.borrow_mut() = model.deck_rows.clone();
        self.layout_deck_rows(self.current_bounds());
        for (index, label) in self.deck_row_labels.iter().enumerate() {
            if let Some(row) = model.deck_rows.get(index) {
                label.setStringValue(&NSString::from_str(&format!(
                    "{:>2}   {}{}",
                    row.mana_cost
                        .map(|cost| cost.to_string())
                        .unwrap_or_else(|| "—".to_owned()),
                    row.name,
                    if row.count > 1 {
                        format!("  ×{}", row.count)
                    } else {
                        String::new()
                    }
                )));
                label.setHidden(false);
            } else {
                label.setHidden(true);
            }
        }
        self.update_hover_preview()?;
        Ok(())
    }

    /// Returns the card row currently under the global cursor while keeping
    /// the overlay click-through. The caller may use this to populate a local
    /// preview cache asynchronously.
    pub fn hovered_card_id(&self) -> Result<Option<String>, OverlayError> {
        require_main_thread()?;
        if !self.panel.isVisible() {
            return Ok(None);
        }
        let mouse = NSEvent::mouseLocation();
        let panel_frame = self.panel.frame();
        let local = NSPoint::new(
            mouse.x - panel_frame.origin.x,
            mouse.y - panel_frame.origin.y,
        );
        let rows = self.deck_rows.borrow();
        Ok(self
            .deck_row_labels
            .iter()
            .zip(rows.iter())
            .find(|(label, _)| {
                let frame = label.frame();
                !label.isHidden()
                    && local.x >= frame.origin.x
                    && local.x <= frame.origin.x + frame.size.width
                    && local.y >= frame.origin.y
                    && local.y <= frame.origin.y + frame.size.height
            })
            .map(|(_, row)| row.card_id.clone()))
    }

    fn current_bounds(&self) -> OverlayBounds {
        let frame = self.panel.frame();
        OverlayBounds::new(
            frame.origin.x,
            frame.origin.y,
            frame.size.width,
            frame.size.height,
        )
    }

    fn layout_deck_rows(&self, bounds: OverlayBounds) {
        let header_lines = self.label.stringValue().to_string().lines().count().max(1);
        for (index, label) in self.deck_row_labels.iter().enumerate() {
            label.setFrame(deck_row_frame(bounds, index, header_lines));
        }
    }

    fn update_hover_preview(&self) -> Result<(), OverlayError> {
        let Some(card_id) = self.hovered_card_id()? else {
            self.preview_panel.orderOut(None);
            return Ok(());
        };
        let rows = self.deck_rows.borrow();
        let Some(row) = rows.iter().find(|row| row.card_id == card_id) else {
            self.preview_panel.orderOut(None);
            return Ok(());
        };
        let bounds = self.current_bounds();
        self.preview_panel.setFrame_display(
            NSRect::new(
                NSPoint::new(bounds.x + bounds.width + 8.0, bounds.y + 30.0),
                NSSize::new(256.0, 384.0),
            ),
            true,
        );
        if let Some(path) = row.preview_image_path.as_deref()
            && let Some(image) =
                NSImage::initWithContentsOfFile(NSImage::alloc(), &NSString::from_str(path))
        {
            self.preview_image.setImage(Some(&image));
            self.preview_image.setHidden(false);
            self.preview_status.setHidden(true);
        } else {
            self.preview_image.setImage(None);
            self.preview_image.setHidden(true);
            self.preview_status
                .setStringValue(&NSString::from_str(&format!("Loading {}…", row.name)));
            self.preview_status.setHidden(false);
        }
        self.preview_panel.orderFrontRegardless();
        Ok(())
    }

    /// Returns whether AppKit currently considers the panel visible.
    pub fn is_visible(&self) -> Result<bool, OverlayError> {
        require_main_thread()?;
        Ok(self.panel.isVisible())
    }

    /// Runs the AppKit event loop for a standalone overlay binary.
    ///
    /// Most applications will instead integrate this host into their existing
    /// main event loop. This call blocks until `NSApplication` terminates.
    pub fn run_event_loop(&self) -> Result<(), OverlayError> {
        require_main_thread()?;
        self._application.run();
        Ok(())
    }

    /// Runs a small native event loop and invokes `tick` immediately, then at
    /// roughly `interval` intervals on AppKit's main thread.
    ///
    /// This is the bridge for a single small native binary: `tick` can poll a
    /// non-blocking observer snapshot, call [`Self::update_model`], and use
    /// [`hearthstone_is_frontmost`] to show or hide the overlay. Between ticks,
    /// AppKit's main run loop remains live for window drawing and events.
    ///
    /// Keep `tick` short. Any blocking log I/O, image recognition, or network
    /// work belongs in the observer worker; this closure should only consume
    /// its latest result and render it. Return [`TickControl::Stop`] to leave
    /// this loop cleanly, or propagate a typed observer error.
    pub fn run_with_tick<F, E>(
        &self,
        interval: Duration,
        mut tick: F,
    ) -> Result<(), RunWithTickError<E>>
    where
        F: FnMut(&OverlayHost) -> Result<TickControl, E>,
    {
        require_main_thread().map_err(RunWithTickError::Overlay)?;
        validate_tick_interval(interval).map_err(RunWithTickError::Overlay)?;

        loop {
            match tick(self).map_err(RunWithTickError::Tick)? {
                TickControl::Continue => {}
                TickControl::Stop => return Ok(()),
            }

            pump_app_events(&self._application, Instant::now() + interval);
        }
    }
}

/// Returns the frontmost process's bundle ID without inspecting its memory,
/// windows, or files. `None` means macOS did not report a frontmost app or it
/// has no bundle identifier.
pub fn frontmost_bundle_id() -> Result<Option<String>, OverlayError> {
    require_main_thread()?;
    Ok(NSWorkspace::sharedWorkspace()
        .frontmostApplication()
        .and_then(|application| application.bundleIdentifier())
        .map(|identifier| identifier.to_string()))
}

/// Returns whether retail Hearthstone is the currently frontmost application.
///
/// This is deliberately only a bundle-ID comparison. It does not attach to,
/// inject into, inspect, or control the game process.
pub fn hearthstone_is_frontmost() -> Result<bool, OverlayError> {
    Ok(is_hearthstone_bundle_id(frontmost_bundle_id()?.as_deref()))
}

fn require_main_thread() -> Result<MainThreadMarker, OverlayError> {
    MainThreadMarker::new().ok_or(OverlayError::NotOnMainThread)
}

fn is_hearthstone_bundle_id(bundle_id: Option<&str>) -> bool {
    bundle_id.is_some_and(|bundle_id| HEARTHSTONE_BUNDLE_IDS.contains(&bundle_id))
}

fn validate_tick_interval(interval: Duration) -> Result<(), OverlayError> {
    if interval.is_zero() {
        Err(OverlayError::InvalidTickInterval)
    } else {
        Ok(())
    }
}

fn pump_app_events(application: &NSApplication, deadline: Instant) {
    // Explicitly dispatch events through NSApplication. This matters for
    // NSStatusItem menu tracking: a bare NSRunLoop pump can draw the item but
    // fail to enter AppKit's event/menu tracking path.
    loop {
        let remaining = deadline.saturating_duration_since(Instant::now());
        if remaining.is_zero() {
            return;
        }
        let limit = NSDate::dateWithTimeIntervalSinceNow(remaining.as_secs_f64());
        let event = application.nextEventMatchingMask_untilDate_inMode_dequeue(
            NSEventMask(NSAnyEventMask.0),
            Some(&limit),
            unsafe { NSDefaultRunLoopMode },
            true,
        );
        if let Some(event) = event {
            application.sendEvent(&event);
        }
    }
}

fn configure_panel(panel: &NSPanel) {
    // `setFloatingPanel(true)` resets an NSPanel to NSFloatingWindowLevel.
    // Apply the status level afterward so the final window level remains
    // above Hearthstone's native-fullscreen surface.
    panel.setFloatingPanel(true);
    panel.setLevel(NSStatusWindowLevel);
    panel.setCollectionBehavior(
        NSWindowCollectionBehavior::CanJoinAllSpaces
            | NSWindowCollectionBehavior::FullScreenAuxiliary
            | NSWindowCollectionBehavior::Stationary
            | NSWindowCollectionBehavior::IgnoresCycle,
    );
    panel.setBecomesKeyOnlyIfNeeded(true);
    panel.setIgnoresMouseEvents(true);
    panel.setHidesOnDeactivate(false);
    panel.setMovableByWindowBackground(false);
    panel.setOpaque(false);
    panel.setBackgroundColor(Some(&NSColor::clearColor()));
    panel.setHasShadow(false);
}

fn configure_score_panel(panel: &NSPanel) {
    configure_panel(panel);
    panel.setHasShadow(true);
}

fn configure_score_surface(surface: &NSBox) {
    surface.setBoxType(objc2_app_kit::NSBoxType::Custom);
    surface.setFillColor(&NSColor::colorWithCalibratedRed_green_blue_alpha(
        0.12, 0.085, 0.025, 0.95,
    ));
    surface.setBorderColor(&NSColor::colorWithCalibratedRed_green_blue_alpha(
        0.66, 0.46, 0.14, 0.98,
    ));
    surface.setBorderWidth(1.5);
    surface.setCornerRadius(8.0);
}

fn configure_score_text(label: &NSTextField) {
    label.setDrawsBackground(false);
    label.setBordered(false);
    label.setBezeled(false);
    label.setEditable(false);
    label.setSelectable(false);
    label.setMaximumNumberOfLines(1);
}

fn configure_score_caption(label: &NSTextField) {
    configure_score_text(label);
    label.setTextColor(Some(&NSColor::colorWithCalibratedRed_green_blue_alpha(
        1.0, 0.94, 0.77, 1.0,
    )));
    label.setFont(Some(&NSFont::boldSystemFontOfSize(13.0)));
}

fn configure_score_detail(label: &NSTextField) {
    configure_score_text(label);
    label.setTextColor(Some(&NSColor::colorWithCalibratedRed_green_blue_alpha(
        0.82, 0.68, 0.39, 1.0,
    )));
    label.setFont(Some(&NSFont::boldSystemFontOfSize(10.5)));
}

fn configure_score_value(label: &NSTextField) {
    configure_score_text(label);
    label.setTextColor(Some(&NSColor::colorWithCalibratedRed_green_blue_alpha(
        1.0, 0.83, 0.30, 1.0,
    )));
    label.setFont(Some(&NSFont::boldSystemFontOfSize(34.0)));
}

fn popup_label(
    text: &str,
    frame: NSRect,
    size: f64,
    color: &NSColor,
    main_thread: MainThreadMarker,
) -> Retained<NSTextField> {
    let label = NSTextField::wrappingLabelWithString(&NSString::from_str(text), main_thread);
    label.setFrame(frame);
    label.setFont(Some(&NSFont::systemFontOfSize(size)));
    label.setTextColor(Some(color));
    label.setDrawsBackground(true);
    label.setBackgroundColor(Some(&NSColor::clearColor()));
    label.setBordered(false);
    label.setBezeled(false);
    label.setEditable(false);
    label.setSelectable(false);
    label.setMaximumNumberOfLines(0);
    label
}

fn configure_label(label: &NSTextField, bounds: OverlayBounds) {
    label.setFrame(label_frame(bounds));
    label.setAutoresizingMask(
        NSAutoresizingMaskOptions::ViewWidthSizable | NSAutoresizingMaskOptions::ViewHeightSizable,
    );
    label.setDrawsBackground(false);
    label.setBordered(false);
    label.setBezeled(false);
    label.setEditable(false);
    label.setSelectable(false);
    label.setTextColor(Some(&NSColor::whiteColor()));
    label.setFont(Some(&NSFont::systemFontOfSize(16.0)));
    label.setMaximumNumberOfLines(0);
}

fn configure_deck_row(label: &NSTextField) {
    label.setDrawsBackground(true);
    label.setBackgroundColor(Some(&NSColor::colorWithCalibratedWhite_alpha(0.04, 0.72)));
    label.setBordered(false);
    label.setBezeled(false);
    label.setEditable(false);
    label.setSelectable(false);
    label.setTextColor(Some(&NSColor::whiteColor()));
    label.setFont(Some(&NSFont::systemFontOfSize(13.0)));
    label.setMaximumNumberOfLines(1);
}

fn configure_preview_status(label: &NSTextField) {
    label.setFrame(NSRect::new(
        NSPoint::new(18.0, 160.0),
        NSSize::new(220.0, 64.0),
    ));
    label.setDrawsBackground(false);
    label.setBordered(false);
    label.setBezeled(false);
    label.setEditable(false);
    label.setSelectable(false);
    label.setTextColor(Some(&NSColor::whiteColor()));
    label.setFont(Some(&NSFont::boldSystemFontOfSize(14.0)));
}

fn deck_row_frame(bounds: OverlayBounds, index: usize, header_lines: usize) -> NSRect {
    const ROW_HEIGHT: f64 = 17.0;
    const HEADER_LINE_HEIGHT: f64 = 19.0;
    let width = (bounds.width - 2.0 * CONTENT_PADDING).max(1.0);
    let top = bounds.height - CONTENT_PADDING - header_lines as f64 * HEADER_LINE_HEIGHT - 6.0;
    NSRect::new(
        NSPoint::new(CONTENT_PADDING, top - (index as f64 + 1.0) * ROW_HEIGHT),
        NSSize::new(width, ROW_HEIGHT - 1.0),
    )
}

fn configure_action_button(button: &NSButton) {
    button.setFrame(action_button_frame());
    button.setFont(Some(&NSFont::systemFontOfSize(12.0)));
    button.setToolTip(Some(&NSString::from_str(
        "Recover missing or incorrect Arena deck cards",
    )));
}

fn label_frame(bounds: OverlayBounds) -> NSRect {
    let width = (bounds.width - 2.0 * CONTENT_PADDING).max(1.0);
    let height = (bounds.height - 2.0 * CONTENT_PADDING).max(1.0);
    NSRect::new(
        NSPoint::new(CONTENT_PADDING, CONTENT_PADDING),
        NSSize::new(width, height),
    )
}

fn action_button_frame() -> NSRect {
    NSRect::new(
        NSPoint::new(0.0, 0.0),
        NSSize::new(ACTION_BUTTON_WIDTH, ACTION_BUTTON_HEIGHT),
    )
}

fn fix_deck_panel_frame(bounds: OverlayBounds) -> NSRect {
    NSRect::new(
        NSPoint::new(
            bounds.x + (bounds.width - CONTENT_PADDING - ACTION_BUTTON_WIDTH).max(0.0),
            bounds.y + (bounds.height - CONTENT_PADDING - ACTION_BUTTON_HEIGHT).max(0.0),
        ),
        NSSize::new(ACTION_BUTTON_WIDTH, ACTION_BUTTON_HEIGHT),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn model_renders_title_then_non_empty_lines() {
        let model = OverlayModel {
            title: "Arena draft".to_owned(),
            lines: vec![
                "Fireball — 82".to_owned(),
                " ".to_owned(),
                "Frostbolt — 75".to_owned(),
            ],
            deck_rows: Vec::new(),
        };

        assert_eq!(
            model.display_text(),
            "Arena draft\nFireball — 82\nFrostbolt — 75"
        );
    }

    #[test]
    fn model_allows_an_empty_view() {
        assert_eq!(OverlayModel::default().display_text(), "");
    }

    #[test]
    fn bounds_reject_non_positive_or_non_finite_sizes() {
        assert!(OverlayBounds::new(0.0, 0.0, 1.0, 1.0).validate().is_ok());
        assert!(matches!(
            OverlayBounds::new(0.0, 0.0, 0.0, 10.0).validate(),
            Err(OverlayError::InvalidBounds(_))
        ));
        assert!(matches!(
            OverlayBounds::new(0.0, 0.0, f64::NAN, 10.0).validate(),
            Err(OverlayError::InvalidBounds(_))
        ));
    }

    #[test]
    fn label_frame_keeps_padding_for_regular_bounds() {
        let frame = label_frame(OverlayBounds::new(0.0, 0.0, 200.0, 100.0));
        assert_eq!(frame.origin, NSPoint::new(CONTENT_PADDING, CONTENT_PADDING));
        assert_eq!(frame.size, NSSize::new(176.0, 76.0));
    }

    #[test]
    fn hearthstone_bundle_comparison_is_exact() {
        assert!(is_hearthstone_bundle_id(Some(HEARTHSTONE_BUNDLE_IDS[0])));
        assert!(is_hearthstone_bundle_id(Some(HEARTHSTONE_BUNDLE_IDS[1])));
        assert!(!is_hearthstone_bundle_id(Some(
            "com.blizzard.hearthstone.beta"
        )));
        assert!(!is_hearthstone_bundle_id(Some("com.apple.Terminal")));
        assert!(!is_hearthstone_bundle_id(None));
    }

    #[test]
    fn tick_interval_cannot_spin_the_main_thread() {
        assert_eq!(
            validate_tick_interval(Duration::ZERO),
            Err(OverlayError::InvalidTickInterval)
        );
        assert!(validate_tick_interval(Duration::from_millis(500)).is_ok());
    }
}
